### ISSUE TITLE
github仓库的合作逻辑

### ISSUE THREAD

**Issue by Borui-L** [dontnet-wuenze/Epidemic-Service-System#2]
不是太懂master现在的地位是什么？是作为生产环境的稳定分支吗？
所以我们所有的开发都应该在user-dev分支上做，然后自行merge或者发一个pull request到develop分支上？
master分支定期拉取稳定的develop分支进行merge，形成生产版本？

**Comment by dontnet-wuenze** [comment]
master 相当于一个 release,每周合并一次
develop 相当于我们开发的主分支
每个人在自己的 xxx-dev 上开发，然后 push 到远程仓库后， merge到远程的develop分支上。
如果遇到 confict, 发出 pull request 我来解决冲突。

**Comment by Borui-L** [comment]
> master 相当于一个 release,每周合并一次 develop 相当于我们开发的主分支 每个人在自己的 xxx-dev 上开发，然后 push 到远程仓库后， merge到远程的develop分支上。 如果遇到 confict, 发出 pull request 我来解决冲突。
